Bookstore/Models/Book.cs
using System;
using System.Collections.Generic;

namespace Bookstore.Models;

public partial class Book
{
    public int BookId { get; set; }

    public string Title { get; set; }

    public string Author { get; set; }

    public string Publisher { get; set; }

    public string Isbn { get; set; }

    public string Classification { get; set; }

    public string Category { get; set; }

    public int PageCount { get; set; }

    public double Price { get; set; }
}

Bookstore/Models/BookstoreContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Models;

public partial class BookstoreContext : DbContext
{
    public BookstoreContext()
    {
    }

    public BookstoreContext(DbContextOptions<BookstoreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Book> Books { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlite("Data Source=Bookstore.sqlite");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasIndex(e => e.BookId, "IX_Books_BookID").IsUnique();

            entity.Property(e => e.BookId).HasColumnName("BookID");
            entity.Property(e => e.Isbn).HasColumnName("ISBN");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Bookstore/Models/EFBookstoreRepository.cs
namespace Bookstore.Models
{
    public class EFBookstoreRepository : IBookstoreRepository
    {
        private BookstoreContext _context;
        public EFBookstoreRepository(BookstoreContext temp) { 
            _context = temp;
        }  
        public IQueryable<Book> Books => _context.Books;
    }
}

Bookstore/Models/IBookstoreRepository.cs
namespace Bookstore.Models
{
    public interface IBookstoreRepository
    {
        public IQueryable<Book> Books { get; }
    }
}

Bookstore/Models/ViewModels/BooksListViewModel.cs
namespace Bookstore.Models.ViewModels
{
    public class BooksListViewModel
    {
        public IQueryable<Book> Books { get; set; }
        public PaginationInfo PaginationInfo { get; set; } = new PaginationInfo();

        public string? CurrentBookType { get; set; }
    }
}

Bookstore/Models/ViewModels/PaginationInfo.cs
namespace Bookstore.Models.ViewModels
{
    public class PaginationInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalNumPages => (int)  Math.Ceiling((decimal) TotalItems / ItemsPerPage);

    }
}

Bookstore/Components/BookTypesViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class BookTypesViewComponent : ViewComponent
    {
        private IBookstoreRepository _repo;
        public BookTypesViewComponent(IBookstoreRepository temp) { 
            _repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedBookType = RouteData?.Values["bookType"];

            var bookTypes = _repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
           
            return View(bookTypes);
        }
    }
}

Bookstore/Controllers/HomeController.cs
using Bookstore.Models;
using Bookstore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookstore.Controllers
{
    public class HomeController : Controller
    {
        private IBookstoreRepository _repo;

        public HomeController(IBookstoreRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(int pageNum, string? bookType)
        {
            int pageSize = 10;

            var listView = new BooksListViewModel
            {
                Books = _repo.Books
                .Where(x => x.Category == bookType || bookType == null)
                .OrderBy(x => x.Title)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = bookType == null ? _repo.Books.Count() : _repo.Books.Where(x => x.Category == bookType).Count()
                },

                CurrentBookType = bookType

            };
            
            return View(listView);
        }

    }
}

Bookstore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model BooksListViewModel

    <h1>Bookstore</h1>
    
    @foreach (Book b in Model.Books)
    {
        <partial name="BookSummary" model="b"/>
    }

<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn" 
    page-class-normal="btn-outline-secondary" page-class-selected="btn-secondary" 
    page-url-bookType="@Model.CurrentBookType" class="btn-group pull-right m-1"></div>

Bookstore/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book

<div class="card m-1 p-1">
    <h4>
        @Model.Title
        <span class="badge rounded-pill bg-black text-white float-end"><small>$@Model.Price</small></span>
    </h4>

    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>
</div>

Bookstore/Views/Shared/Components/BookTypes/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model IEnumerable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-bookType="" asp-route-pageNum="">Home</a>

    @foreach (string bt in Model ?? Enumerable.Empty<string>())
    {
        <a class="btn @(bt == ViewBag.SelectedBookType ? "btn-secondary" : "btn-outline-secondary") asp-controller="Home" asp-action="Index" asp-route-bookType="@bt" asp-route-pageNum="1">@bt</a>
    }
</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookstore.styles.css" asp-append-version="true" />
</head>
<body>
@*     <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action=""></a> Add new navbar item here
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">BOOKSTORE</span>
    </div>
    <div class="row m-1 p-1">
       <div class="col-3">
           <vc:book-types />
       </div>
       <div class="container col-9">
           <main role="main" class="pb-3">
               @RenderBody()
           </main>
       </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>